MVCNupat/Models/ErrorViewModel.cs
namespace MVCNupat.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCNupat/Models/Teacher.cs
using System.ComponentModel.DataAnnotations;

namespace MVCNupat.Models
{
    public class Teacher
    {
        [Key]
        public int TeacherId { get; set; }
        [Required]
        public string TeacherName { get; set; }
        [Required]
        public string Age { get; set; }
        public double salary { get; set; }
    }
}

MVCNupat/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCNupat.Models;
using System.Diagnostics;

namespace MVCNupat.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCNupat/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using MVCNupat.Data;
using MVCNupat.Models;

namespace MVCNupat.Controllers
{
    public class TeacherController : Controller
    {
        private readonly AppDbContext _db;

        public TeacherController(AppDbContext db)
        {
            _db = db;
        }


        public IActionResult Index()
        {
            IEnumerable<Teacher> getTeach = _db.Teachers;
            return View(getTeach);
        }
    }
}

MVCNupat/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVCNupat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCNupat</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCNupat.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCNupat</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li>
                            <a asp-controller="Teacher" asp-action="Index">Teacher</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVCNupat - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVCNupat/Views/Teacher/Index.cshtml
@model IEnumerable<Teacher>

<a asp-controller="Fishs" asp-action="Create">Create New Fish</a>
<table class="table table-bordered table-striped" style="100%">
    <thead>
       <tr>
            <th>
               Teachers Name
            </th>
            <th>
               Age
            </th>
            <th>
                Salary
            </th>
       </tr>
    </thead>
    <tbody>
        @foreach(var Loops in Model)
        {
            <tr>
                <td style="width=50%">
                    @Loops.TeacherName
                </td>
                <td style="width=50%">
                    @Loops.Age
                </td>
                <td>
                    @Loops.salary
                </td>
                <td>
                    <a asp-controller="Fishs" asp-action="Update" asp-route-Id="">Update</a>
                </td>
                <td>
                    <a asp-controller="Fishs" asp-action="Delete" asp-route-id="">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>